---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 3068

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
      - recipe[postgresql::default]
    attributes:
      postgresql:
        username: 'pguser'
        password: 'pg123'
        database_name:  'pgdb'
